[package]
name = "rust_fluid_3d"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
rayon = "1.10.0"
nalgebra = "0.33.2"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
csv = "1.1"
